### ISSUE TITLE
The data in the experiment

### ISSUE THREAD

**Issue by duguangmeiyu** [GaryMataev/DeepRED#2]
Hello, can you provide the data in the experiment, I did not find the experimental picture in the paper.

**Comment by GaryMataev** [comment]
Hi,
Denoising is taken from http://www.cs.tut.fi/~foi/GCF-BM3D/
Deblurring is taken from https://www4.comp.polyu.edu.hk/~cslzhang/NCSR.htm
Super-resolution is taken from (Set5, Set14) http://vllab.ucmerced.edu/wlai24/LapSRN/

**Comment by duguangmeiyu** [comment]
Know it,thank you very much.
